version: '3'

tasks:
  clean:
    desc: "Clean the database and remove all migrations"
    cmds:
      - rm -f ./storage/sso.db
      - touch ./storage/sso.db

  force-version:
    desc: "Force migration version"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test --force-version=1

  migrate:
    desc: "Run migrations for the project"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
    sources:
      - cmd/migrator/main.go
      - tests/migrations
    generates:
      - storage/sso.db

  clean-and-migrate:
    desc: "Clean the database and then run migrations"
    cmds:
      - task: clean
      - task: force-version
      - task: migrate
    sources:
      - cmd/migrator/main.go
      - tests/migrations
    generates:
      - storage/sso.db
